Fix Crash when a Customization TextField is empty
OpenCubicChunks/CubicWorldGen pull request #4
Opened 2018-09-21 10:05 UTC by Shad0wlife

The empty string caused the  String parsing for the textfields
- expectedBaseHeight
- expectedHeightVariation
- actualHeight
to fail with a NumberFormatException, resulting in a crash.
This fix catches that exception, turns the cursor in the field red (and as soon as a proper value is detected back to grey) and if the menu is left (by clicking Done) with an empty field, that field resets to default.

2018-09-21 18:21 UTC, Niko-sk2x commented
I really don't like the idea of catching an exception as a normal expected behavior. But can't fix stupid Java library design here...

2018-09-21 18:22 UTC, Niko-sk2x requested changes

2018-09-21 18:22 UTC, Niko-sk2x commented on src/main/java/io/github/opencubicchunks/cubicchunks/cubicgen/customcubic/gui/AdvancedTerrainShapeTab.java
> +		}
Formatting

2018-09-21 19:38 UTC, Shad0wlife commented
I actually don't like the catching as a solution either, but any alternative would really only result in wrapping the catching in some method - as you said, sadly that behaviour is Java sided.
If you would prefer that over the try/catch - the alternative would be getting the string first and then checking if it's empty and acting based on that. Would basically be the same thing - just not with an exception.

`
String textValue = this.textfield.getText();
if(textValue.equals("")){
    //Red cursor
}else{
    //Save value and normal cursor
}
`

Also, what do you think about the red cursor? Ok like that or too much?

2018-09-22 13:11 UTC, Barteks2x commented
Red cursor is fine. As for is empty check - that would also break. With too big or too small integers.

2018-09-26 16:22 UTC, Niko-sk2x commented
It still has tabs

2018-09-30 19:24 UTC, Niko-sk2x commented
Did you actually test it? I don't see anything that handles doing things while typing into the text fields and I'm pretty sure there was something.

2018-09-30 19:30 UTC, Shad0wlife commented
How do you mean "handles doing things while typing into the text field"?
The modified method seems to be the only one to actually parse the field contents.
If you mean by testing that I ran it, emptied the fields, the cursor turned red - and grey again when I entered something - and that after leaving the menu, it's back at default, then yes.
If you want an actual testing procedure, please give me guidelines for that - just be aware that I don't know how to actually write unit tests :)

2018-09-30 20:07 UTC, Barteks2x commented
Unit tests in Minecraft mods are rare so I don't demand it. If it works, it's ok.

2018-09-30 20:08 UTC, merged